show_downloads: true
google_analytics:
title: <p align="center"> Aravind Vadamalaimuthu </p>
logo: /assets/img/av.jpeg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/aravindv7/">Resume</a> |
  <a href="https://www.linkedin.com/in/aravindv7/">LinkedIn</a> |
  <a href="https://github.com/aravindvcyber/">GitHub</a>
  
  <br>   
  Fullstack developer learning Machine Learning and Datascience.
  <br>
  </p>



theme: jekyll-theme-minimal

